import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "labial-rojo-velvet",
    name: "Labial Mate Velvet",
    brand: "Studio Glow",
    category: "labial",
    colorHex: "#D6294B",
    openedDateLabel: "3 ene 2025",
    expiryDateLabel: "3 ene 2026",
    expiryStatus: "active",
    expiryText: "Caduca en 4 meses",
    usageCount: 28,
    occasions: ["diario", "trabajo", "evento"],
    notes: "Acabado mate, dura toda la jornada sin retocar.",
  },
  {
    id: "base-fluida-nova",
    name: "Base Fluida Piel Natural",
    brand: "Nova Cosmetics",
    category: "base",
    colorHex: "#E8B98C",
    openedDateLabel: "10 feb 2025",
    expiryDateLabel: "10 ago 2025",
    expiryStatus: "expiring-soon",
    expiryText: "Caduca en 9 días",
    usageCount: 54,
    occasions: ["diario", "trabajo"],
    notes: "Cobertura media, se mezcla bien con protector solar.",
  },
  {
    id: "rimel-volumen-aurum",
    name: "Rímel Volumen XL",
    brand: "Aurum",
    category: "rimel",
    colorHex: "#1B1B1F",
    openedDateLabel: "2 jun 2025",
    expiryDateLabel: "2 sep 2025",
    expiryStatus: "expiring-soon",
    expiryText: "Caduca en 3 días",
    usageCount: 41,
    occasions: ["diario", "noche", "evento"],
    notes: "Cepillo curvo, ideal para pestañas rectas.",
  },
  {
    id: "sombra-paleta-urban",
    name: "Paleta Sombras Sunset",
    brand: "Urban Muse",
    category: "sombra",
    colorHex: "#C9793B",
    openedDateLabel: "18 nov 2024",
    expiryDateLabel: "18 nov 2025",
    expiryStatus: "active",
    expiryText: "Caduca en 2 meses",
    usageCount: 19,
    occasions: ["noche", "evento", "finde"],
  },
  {
    id: "delineador-gel-lumen",
    name: "Delineador en Gel",
    brand: "Lumen",
    category: "delineador",
    colorHex: "#111114",
    openedDateLabel: "5 dic 2024",
    expiryDateLabel: "5 jun 2025",
    expiryStatus: "expired",
    expiryText: "Caducó hace 2 meses",
    usageCount: 33,
    occasions: ["noche", "evento"],
    notes: "Trazo preciso, aplicar con pincel biselado fino.",
  },
  {
    id: "rubor-polvo-petal",
    name: "Rubor en Polvo Coral",
    brand: "Petal & Co",
    category: "rubor",
    colorHex: "#F17E8C",
    openedDateLabel: "22 ene 2025",
    expiryDateLabel: "22 ene 2027",
    expiryStatus: "active",
    expiryText: "Caduca en 16 meses",
    usageCount: 12,
    occasions: ["diario", "finde"],
  },
  {
    id: "polvo-compacto-velvet",
    name: "Polvo Compacto Matificante",
    brand: "Velvet Lab",
    category: "polvo",
    colorHex: "#EAC9A6",
    openedDateLabel: "14 mar 2025",
    expiryDateLabel: "14 mar 2026",
    expiryStatus: "active",
    expiryText: "Caduca en 6 meses",
    usageCount: 37,
    occasions: ["diario", "trabajo"],
  },
  {
    id: "bronceador-glow-sunkiss",
    name: "Bronceador Glow",
    brand: "Blush House",
    category: "bronceador",
    colorHex: "#B97648",
    openedDateLabel: "9 abr 2025",
    expiryDateLabel: "9 abr 2027",
    expiryStatus: "active",
    expiryText: "Caduca en 19 meses",
    usageCount: 8,
    occasions: ["finde", "evento"],
  },
  {
    id: "primer-poros-matte",
    name: "Primer Minimizador de Poros",
    brand: "Matte Co",
    category: "primer",
    colorHex: "#DCC9B8",
    openedDateLabel: "30 dic 2024",
    expiryDateLabel: "30 jun 2025",
    expiryStatus: "expired",
    expiryText: "Caducó hace 2 meses",
    usageCount: 45,
    occasions: ["diario", "trabajo", "evento"],
  },
  {
    id: "corrector-luminoso-lumen",
    name: "Corrector Luminoso",
    brand: "Lumen",
    category: "corrector",
    colorHex: "#F0C39B",
    openedDateLabel: "1 jul 2025",
    expiryDateLabel: "1 ene 2026",
    expiryStatus: "expiring-soon",
    expiryText: "Caduca en 14 días",
    usageCount: 22,
    occasions: ["diario", "trabajo"],
  },
  {
    id: "labial-nude-aurum",
    name: "Labial Cremoso Nude",
    brand: "Aurum",
    category: "labial",
    colorHex: "#C48B72",
    openedDateLabel: "15 may 2025",
    expiryDateLabel: "15 may 2026",
    expiryStatus: "active",
    expiryText: "Caduca en 8 meses",
    usageCount: 15,
    occasions: ["diario", "trabajo"],
  },
  {
    id: "sombra-individual-noche",
    name: "Sombra Individual Midnight",
    brand: "Urban Muse",
    category: "sombra",
    colorHex: "#3A2E52",
    openedDateLabel: "20 ago 2024",
    expiryDateLabel: "20 ago 2025",
    expiryStatus: "expired",
    expiryText: "Caducó hace 3 semanas",
    usageCount: 9,
    occasions: ["noche", "evento"],
  },
  {
    id: "rimel-waterproof-nova",
    name: "Rímel Waterproof",
    brand: "Nova Cosmetics",
    category: "rimel",
    colorHex: "#151517",
    openedDateLabel: "1 ago 2025",
    expiryDateLabel: "1 nov 2025",
    expiryStatus: "active",
    expiryText: "Caduca en casi 2 meses",
    usageCount: 6,
    occasions: ["finde", "evento", "noche"],
  },
  {
    id: "base-stick-studio",
    name: "Base en Stick Cobertura Alta",
    brand: "Studio Glow",
    category: "base",
    colorHex: "#D9A576",
    openedDateLabel: "28 jul 2025",
    expiryDateLabel: "28 ene 2026",
    expiryStatus: "expiring-soon",
    expiryText: "Caduca en 20 días",
    usageCount: 17,
    occasions: ["trabajo", "evento"],
  },
];

export const DASHBOARD_SUGGESTION = {
  occasionLabel: "Día de oficina",
  productIds: ["base-fluida-nova", "labial-nude-aurum", "polvo-compacto-velvet"],
};
